# Generated by Django 4.0.6 on 2022-08-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_destinations_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='destination_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
