# Generated by Django 4.0.6 on 2022-08-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_backpackingtours_bikingtours_roadtours_weekendtours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikingtours',
            name='destination_price',
        ),
        migrations.RemoveField(
            model_name='bikingtours',
            name='inner_details',
        ),
        migrations.RemoveField(
            model_name='bikingtours',
            name='inner_title',
        ),
        migrations.RemoveField(
            model_name='bikingtours',
            name='inner_video',
        ),
        migrations.RemoveField(
            model_name='weekendtours',
            name='destination_price',
        ),
        migrations.RemoveField(
            model_name='weekendtours',
            name='inner_details',
        ),
        migrations.RemoveField(
            model_name='weekendtours',
            name='inner_title',
        ),
        migrations.RemoveField(
            model_name='weekendtours',
            name='inner_video',
        ),
        migrations.AlterField(
            model_name='bikingtours',
            name='new_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bikingtours',
            name='old_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
