# Generated by Django 4.0.6 on 2022-08-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_bikingtours_destination_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bikingtours',
            new_name='bikingtrip',
        ),
    ]
