# Generated by Django 4.0.6 on 2022-08-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_backpackingtours_backpackingtrip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backpackingtrip',
            name='destination_price',
        ),
        migrations.RemoveField(
            model_name='backpackingtrip',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='backpackingtrip',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='bikingtrip',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='bikingtrip',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='roadtrip',
            name='destination_price',
        ),
        migrations.RemoveField(
            model_name='roadtrip',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='roadtrip',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='weekendtrip',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='weekendtrip',
            name='old_price',
        ),
    ]
