# Generated by Django 4.0.6 on 2022-08-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_populartrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekendtrip',
            name='mode',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekendtrip',
            name='mode_price',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
