# Generated by Django 4.0.6 on 2022-08-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_alltrip_batch1_alter_alltrip_batch2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltrip',
            name='inner_video',
        ),
        migrations.RemoveField(
            model_name='backpackingtrip',
            name='inner_video',
        ),
        migrations.RemoveField(
            model_name='bikingtrip',
            name='inner_video',
        ),
        migrations.RemoveField(
            model_name='populartrip',
            name='inner_video',
        ),
        migrations.RemoveField(
            model_name='roadtrip',
            name='inner_video',
        ),
        migrations.RemoveField(
            model_name='weekendtrip',
            name='inner_video',
        ),
        migrations.AddField(
            model_name='alltrip',
            name='relatedit1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alltrip',
            name='relatedit2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alltrip',
            name='relatedprice1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alltrip',
            name='relatedprice2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alltrip',
            name='relatedtour1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alltrip',
            name='relatedtour2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alltrip',
            name='reltourimg1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='alltrip',
            name='reltourimg2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='backpackingtrip',
            name='relatedit1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='backpackingtrip',
            name='relatedit2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='backpackingtrip',
            name='relatedprice1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='backpackingtrip',
            name='relatedprice2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='backpackingtrip',
            name='relatedtour1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='backpackingtrip',
            name='relatedtour2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='backpackingtrip',
            name='reltourimg1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='backpackingtrip',
            name='reltourimg2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='bikingtrip',
            name='relatedit1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bikingtrip',
            name='relatedit2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bikingtrip',
            name='relatedprice1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bikingtrip',
            name='relatedprice2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bikingtrip',
            name='relatedtour1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bikingtrip',
            name='relatedtour2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bikingtrip',
            name='reltourimg1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='bikingtrip',
            name='reltourimg2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='populartrip',
            name='relatedit1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='populartrip',
            name='relatedit2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='populartrip',
            name='relatedprice1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='populartrip',
            name='relatedprice2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='populartrip',
            name='relatedtour1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='populartrip',
            name='relatedtour2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='populartrip',
            name='reltourimg1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='populartrip',
            name='reltourimg2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='roadtrip',
            name='relatedit1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='roadtrip',
            name='relatedit2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='roadtrip',
            name='relatedprice1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='roadtrip',
            name='relatedprice2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='roadtrip',
            name='relatedtour1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='roadtrip',
            name='relatedtour2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='roadtrip',
            name='reltourimg1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='roadtrip',
            name='reltourimg2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='weekendtrip',
            name='relatedit1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='weekendtrip',
            name='relatedit2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='weekendtrip',
            name='relatedprice1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='weekendtrip',
            name='relatedprice2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='weekendtrip',
            name='relatedtour1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='weekendtrip',
            name='relatedtour2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='weekendtrip',
            name='reltourimg1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='weekendtrip',
            name='reltourimg2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
