# Generated by Django 4.0.6 on 2022-09-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_trekking_alltrip_expect3_alltrip_expect4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='populartrip',
        ),
        migrations.DeleteModel(
            name='trekking',
        ),
    ]
