# Generated by Django 4.0.6 on 2022-09-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_populartrip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='populartrip',
        ),
    ]
