# Generated by Django 4.0.6 on 2022-09-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_trekking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trekking',
            new_name='trekkings',
        ),
    ]
