# Generated by Django 4.0.6 on 2022-09-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_trekking_trekkings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trekkings',
            new_name='firsts',
        ),
    ]
