# Generated by Django 4.0.6 on 2022-09-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_trekkings_firsts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alltrip',
        ),
        migrations.DeleteModel(
            name='backpackingtrip',
        ),
        migrations.DeleteModel(
            name='bhutantrip',
        ),
        migrations.DeleteModel(
            name='bikingtrip',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='destinations',
        ),
        migrations.DeleteModel(
            name='dubaitrip',
        ),
        migrations.DeleteModel(
            name='firsts',
        ),
        migrations.DeleteModel(
            name='himachaltrip',
        ),
        migrations.DeleteModel(
            name='kashmirtrip',
        ),
        migrations.DeleteModel(
            name='lehtrip',
        ),
        migrations.DeleteModel(
            name='meghalayatrip',
        ),
        migrations.DeleteModel(
            name='populartrip',
        ),
        migrations.DeleteModel(
            name='roadtrip',
        ),
        migrations.DeleteModel(
            name='sikkimtrip',
        ),
        migrations.DeleteModel(
            name='spititrip',
        ),
        migrations.DeleteModel(
            name='weekendtrip',
        ),
    ]
